### ISSUE TITLE
Frozen access to volumio.local

### ISSUE THREAD

**Issue by elcuevero** [volumio/Volumio2-UI#516]
volumio.local is not reacheable. This only happens when listening to webradio, no station in particular. sometimes it's when switching between stations. 90% of the time a volumio vrestart will mak it respond, the rest of the time an mpd restart.
http://logs.volumio.org/volumio/oDNqzvK.html

**Comment by xipmix** [comment]
Thanks for the log - it is most helpful. It looks like  You are getting the same error as volumio/Volumio2#1553 . Some commentary to help digest the log:

```
May 24 08:04:48 volumio volumio[783]: error:  TypeError: Cannot read property '0' of undefined
May 24 08:04:48 volumio volumio[783]: at /volumio/app/plugins/music_service/upnp_browser/index.js:83:67
May 24 08:04:48 volumio volumio[783]: at /volumio/app/plugins/music_service/upnp_browser/index.js:596:21
May 24 08:04:48 volumio volumio[783]: at Parser. (/volumio/node_modules/xml2js/lib/xml2js.js:489:18)
May 24 08:04:48 volumio volumio[783]: at emitOne (events.js:96:13)
May 24 08:04:48 volumio volumio[783]: at Parser.emit (events.js:188:7)
May 24 08:04:48 volumio volumio[783]: at Object.onclosetag (/volumio/node_modules/xml2js/lib/xml2js.js:447:26)
May 24 08:04:48 volumio volumio[783]: at emit (/volumio/node_modules/sax/lib/sax.js:640:35)
May 24 08:04:48 volumio volumio[783]: at emitNode (/volumio/node_modules/sax/lib/sax.js:645:5)
May 24 08:04:48 volumio volumio[783]: at closeTag (/volumio/node_modules/sax/lib/sax.js:905:7)
May 24 08:04:48 volumio volumio[783]: at Object.write (/volumio/node_modules/sax/lib/sax.js:1452:13)
May 24 08:04:48 volumio volumio[783]: at Parser.exports.Parser.Parser.parseString (/volumio/node_modules/xml2js/lib/xml2js.js:508:31)
May 24 08:04:48 volumio volumio[783]: at Parser.parseString (/volumio/node_modules/xml2js/lib/xml2js.js:7:59)
May 24 08:04:48 volumio volumio[783]: at /volumio/app/plugins/music_service/upnp_browser/index.js:595:24
May 24 08:04:48 volumio volumio[783]: at Request.handleRequestResponse [as _callback] (/volumio/node_modules/unirest/index.js:463:26)
May 24 08:04:48 volumio volumio[783]: at Request.self.callback (/volumio/node_modules/unirest/node_modules/request/request.js:187:22)
May 24 08:04:48 volumio volumio[783]: at emitTwo (events.js:106:13)
```
This repeats for some time. Something unusual happens here
```
May 24 10:17:50 volumio avahi-daemon[497]: Received response from host 10.0.0.70 with invalid source port 62295 on interface 'wlan0.0'
May 24 10:17:52 volumio avahi-daemon[497]: Received response from host 10.0.0.70 with invalid source port 62295 on interface 'wlan0.0'
May 24 10:17:54 volumio avahi-daemon[497]: Received response from host 10.0.0.70 with invalid source port 62295 on interface 'wlan0.0'
May 24 10:17:58 volumio avahi-daemon[497]: Received response from host 10.0.0.70 with invalid source port 62295 on interface 'wlan0.0'
May 24 10:17:58 volumio avahi-daemon[497]: Invalid legacy unicast query packet.
May 24 10:17:58 volumio avahi-daemon[497]: Invalid legacy unicast query packet.
May 24 10:17:58 volumio avahi-daemon[497]: Invalid legacy unicast query packet.
May 24 10:17:59 volumio avahi-daemon[497]: Received response from host 10.0.0.70 with invalid source port 62295 on interface 'wlan0.0'
May 24 10:17:59 volumio avahi-daemon[497]: Received response from host 10.0.0.70 with invalid source port 62295 on interface 'wlan0.0'
May 24 10:18:00 volumio avahi-daemon[497]: Received response from host 10.0.0.70 with invalid source port 62295 on interface 'wlan0.0'
May 24 10:18:01 volumio avahi-daemon[497]: Received response from host 10.0.0.70 with invalid source port 62295 on interface 'wlan0.0'
```
but then wer're back to the tracebacks.
Looks like a USB got removed which made volumio unhappy
```
May 24 10:19:14 volumio kernel: usb 1-1: USB disconnect, device number 2
May 24 10:19:14 volumio udisks-glue[445]: Device file /dev/sda1 unmounted from /media/C428-375E
May 24 10:19:14 volumio udisks-glue[445]: Device file /dev/sda1 removed
May 24 10:19:14 volumio udisks-glue[445]: Device file /dev/sda removed
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
...
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: FAT-fs (sda1): Directory bread(block 16384) failed
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: FAT-fs (sda1): Directory bread(block 16385) failed
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: FAT-fs (sda1): Directory bread(block 16386) failed
...
```
Then we start to get some semblance of normality
```
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: blk_partition_remap: fail for partition 1
May 24 10:19:15 volumio kernel: FAT-fs (sda1): unable to read boot sector to mark fs as dirty
May 24 10:19:15 volumio volumio[783]: info: parsing response...
May 24 10:19:15 volumio volumio[783]: info: parsing response...
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::parseState
May 24 10:19:15 volumio volumio[783]: info: Command Router : Notfying DB Updatetrue
May 24 10:19:15 volumio volumio[783]: info: CoreCommandRouter::Close All Modals sent
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::parseState
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::pushState
May 24 10:19:15 volumio volumio[783]: info: CoreCommandRouter::servicePushState
May 24 10:19:15 volumio volumio[783]: info: CoreStateMachine::syncState
May 24 10:19:15 volumio volumio[783]: info: CorePlayQueue::getTrack 0
May 24 10:19:15 volumio volumio[783]: info: Received update from a service different from the one supposed to be playing music. Skipping notification.Current webradio Received mpd
May 24 10:19:15 volumio volumio[783]: info: ------------------------------ 503ms
May 24 10:19:15 volumio volumio[783]: info: MPD Database updated - AlbumList cache refreshed
May 24 10:19:15 volumio volumio[783]: info:
May 24 10:19:15 volumio volumio[783]: ---------------------------- MPD announces state update: database
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::sendMpdCommand status
May 24 10:19:15 volumio volumio[783]: info:
May 24 10:19:15 volumio volumio[783]: ---------------------------- MPD announces state update: update
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::getState
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::sendMpdCommand status
May 24 10:19:15 volumio volumio[783]: info: sending command...
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::getState
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::sendMpdCommand status
May 24 10:19:15 volumio volumio[783]: info: sending command...
May 24 10:19:15 volumio volumio[783]: info: sending command...
May 24 10:19:15 volumio volumio[783]: info: parsing response...
May 24 10:19:15 volumio volumio[783]: info: parsing response...
May 24 10:19:15 volumio volumio[783]: info: parsing response...
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::parseState
May 24 10:19:15 volumio volumio[783]: info: Command Router : Notfying DB Updatefalse
May 24 10:19:15 volumio volumio[783]: info: CoreCommandRouter::Close All Modals sent
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::parseState
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::parseState
May 24 10:19:15 volumio volumio[783]: info: ControllerMpd::pushState
May 24 10:19:15 volumio volumio[783]: info: CoreCommandRouter::servicePushState
```
but then it's back to tracebacks
```
May 24 10:19:20 volumio volumio[783]: info: CorePlayQueue::getTrack 0
May 24 10:19:20 volumio volumio[783]: info: Received update from a service different from the one supposed to be playing music. Skipping notification.Current webradio Received mpd
May 24 10:19:20 volumio volumio[783]: info: ------------------------------ 276ms
May 24 10:19:43 volumio volumio[783]: error:  TypeError: Cannot read property '0' of undefined
May 24 10:19:43 volumio volumio[783]: at /volumio/app/plugins/music_service/upnp_browser/index.js:83:67
May 24 10:19:43 volumio volumio[783]: at /volumio/app/plugins/music_service/upnp_browser/index.js:596:21
May 24 10:19:43 volumio volumio[783]: at Parser. (/volumio/node_modules/xml2js/lib/xml2js.js:489:18)
May 24 10:19:43 volumio volumio[783]: at emitOne (events.js:96:13)
May 24 10:19:43 volumio volumio[783]: at Parser.emit (events.js:188:7)
May 24 10:19:43 volumio volumio[783]: at Object.onclosetag (/volumio/node_modules/xml2js/lib/xml2js.js:447:26)
May 24 10:19:43 volumio volumio[783]: at emit (/volumio/node_modules/sax/lib/sax.js:640:35)
May 24 10:19:43 volumio volumio[783]: at emitNode (/volumio/node_modules/sax/lib/sax.js:645:5)
May 24 10:19:43 volumio volumio[783]: at closeTag (/volumio/node_modules/sax/lib/sax.js:905:7)
May 24 10:19:43 volumio volumio[783]: at Object.write (/volumio/node_modules/sax/lib/sax.js:1452:13)
May 24 10:19:43 volumio volumio[783]: at Parser.exports.Parser.Parser.parseString (/volumio/node_modules/xml2js/lib/xml2js.js:508:31)
May 24 10:19:43 volumio volumio[783]: at Parser.parseString (/volumio/node_modules/xml2js/lib/xml2js.js:7:59)
May 24 10:19:43 volumio volumio[783]: at /volumio/app/plugins/music_service/upnp_browser/index.js:595:24
May 24 10:19:43 volumio volumio[783]: at Request.handleRequestResponse [as _callback] (/volumio/node_modules/unirest/index.js:463:26)
May 24 10:19:43 volumio volumio[783]: at Request.self.callback (/volumio/node_modules/unirest/node_modules/request/request.js:187:22)
May 24 10:19:43 volumio volumio[783]: at emitTwo (events.js:106:13)
```
At last it comes good for a while
```
May 24 10:23:09 volumio volumio[783]: info: CoreCommandRouter::executeOnPlugin: webradio , handleBrowseUri
May 24 10:23:09 volumio volumio[783]: info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
May 24 10:23:11 volumio volumio[783]: info: CoreCommandRouter::executeOnPlugin: webradio , handleBrowseUri
May 24 10:23:12 volumio volumio[783]: info: CoreCommandRouter::volumioAddQueueItems
May 24 10:23:12 volumio volumio[783]: info: CoreStateMachine::addQueueItems
May 24 10:23:12 volumio volumio[783]: info: CorePlayQueue::addQueueItems
May 24 10:23:12 volumio volumio[783]: info: Adding Item to queue: http://cassini.shoutca.st:9300/stream2
May 24 10:23:12 volumio volumio[783]: info: CorePlayQueue::saveQueue
May 24 10:23:12 volumio volumio[783]: info: CoreCommandRouter::volumioPushQueue
May 24 10:23:12 volumio volumio[783]: info: interfaceApi::pushQueue
May 24 10:23:14 volumio volumio[783]: info: CoreStateMachine::updateTrackBlock
May 24 10:23:14 volumio volumio[783]: info: CorePlayQueue::getTrackBlock
May 24 10:23:14 volumio volumio[783]: info: CoreCommandRouter::volumioPlay
May 24 10:23:14 volumio volumio[783]: UNSET VOLATILE
May 24 10:23:14 volumio volumio[783]: info: CoreStateMachine::play index 342
May 24 10:23:14 volumio volumio[783]: info: CoreStateMachine::setConsumeUpdateService undefined
May 24 10:23:14 volumio volumio[783]: info: CoreStateMachine::stop
May 24 10:23:14 volumio volumio[783]: info: CoreStateMachine::setConsumeUpdateService undefined
May 24 10:23:14 volumio volumio[783]: UNSET VOLATILE
May 24 10:23:14 volumio volumio[783]: info: CoreStateMachine::play index undefined
May 24 10:23:14 volumio volumio[783]: info: CoreStateMachine::setConsumeUpdateService undefined
May 24 10:23:14 volumio volumio[783]: info: CorePlayQueue::getTrack 342
May 24 10:23:14 volumio volumio[783]: info: CoreStateMachine::startPlaybackTimer
May 24 10:23:14 volumio volumio[783]: info: CorePlayQueue::getTrack 342
May 24 10:23:14 volumio volumio[783]: info: [1527157394594] ControllerWebradio::clearAddPlayTrack
May 24 10:23:14 volumio volumio[783]: info: ControllerMpd::sendMpdCommand stop
May 24 10:23:14 volumio volumio[783]: info: sending command...
May 24 10:23:16 volumio volumio[783]: info: parsing response...
May 24 10:23:16 volumio volumio[783]: info: ControllerMpd::sendMpdCommand clear
May 24 10:23:16 volumio volumio[783]: info: sending command...
May 24 10:23:16 volumio volumio[783]: info:
May 24 10:23:16 volumio volumio[783]: ---------------------------- MPD announces system playlist update
May 24 10:23:16 volumio volumio[783]: info: Ignoring MPD Status Update
May 24 10:23:16 volumio volumio[783]: info: parsing response...
May 24 10:23:16 volumio volumio[783]: info: ControllerMpd::sendMpdCommand load "http://cassini.shoutca.st:9300/stream2"
May 24 10:23:16 volumio volumio[783]: info: sending command...
May 24 10:23:16 volumio volumio[783]: info:
May 24 10:23:16 volumio volumio[783]: info: ------------------------------ 133ms
May 24 10:23:16 volumio volumio[783]: info: ControllerMpd::sendMpdCommand add "http://cassini.shoutca.st:9300/stream2"
May 24 10:23:16 volumio volumio[783]: info: sending command...
May 24 10:23:16 volumio volumio[783]: info:
May 24 10:23:16 volumio volumio[783]: ---------------------------- MPD announces system playlist update
May 24 10:23:16 volumio volumio[783]: info: Ignoring MPD Status Update
May 24 10:23:16 volumio volumio[783]: info: parsing response...
May 24 10:23:16 volumio volumio[783]: info: CoreStateMachine::setConsumeUpdateService mpd
May 24 10:23:16 volumio volumio[783]: info: ControllerMpd::sendMpdCommand play
May 24 10:23:16 volumio volumio[783]: info: sending command...
May 24 10:23:16 volumio volumio[783]: info: ------------------------------ 58ms
May 24 10:23:16 volumio volumio[783]: info: parsing response...
May 24 10:23:18 volumio volumio[783]: info:
May 24 10:23:18 volumio volumio[783]: ---------------------------- MPD announces state update: player
May 24 10:23:18 volumio volumio[783]: info: ControllerMpd::getState
May 24 10:23:18 volumio volumio[783]: info: ControllerMpd::sendMpdCommand status
May 24 10:23:18 volumio kernel: pcm512x 1-004d: No SCLK, using BCLK: -2
May 24 10:23:18 volumio volumio[783]: info: sending command...
May 24 10:23:18 volumio volumio[783]: info:
```
and thrn we hit the same problem as the other issue, with last.fm access
```
May 24 10:23:19 volumio volumio[783]: info: ------------------------------ 1166ms
May 24 10:23:20 volumio volumio[783]: info: Pushing Favourites {"service":"webradio","uri":"http://8.38.78.173:8210","favourite":false}
May 24 10:23:20 volumio volumio[783]: info: Pushing Favourites {"service":"webradio","uri":"http://cassini.shoutca.st:9300/stream2","favourite":false}
May 24 10:23:20 volumio volumio[783]: info: Pushing Favourites {"service":"webradio","uri":"http://cassini.shoutca.st:9300/stream2","favourite":false}
May 24 10:23:20 volumio volumio[783]: info: Pushing Favourites {"service":"webradio","uri":"http://cassini.shoutca.st:9300/stream2","favourite":false}
May 24 10:23:20 volumio volumio[783]: info: Pushing Favourites {"service":"webradio","uri":"http://cassini.shoutca.st:9300/stream2","favourite":false}
May 24 10:23:21 volumio volumio[783]: info: [LastFM] Error: Authentication Failed - You do not have permissions to access the service
May 24 10:23:22 volumio volumio[783]: info: [LastFM] Error: Authentication Failed - You do not have permissions to access the service
May 24 10:23:50 volumio volumio[783]: info: [LastFM] Error: Authentication Failed - You do not have permissions to access the service
May 24 10:23:53 volumio volumio[783]: error:  TypeError: Cannot read property '0' of undefined
May 24 10:23:53 volumio volumio[783]: at /volumio/app/plugins/music_service/upnp_browser/index.js:78:52
May 24 10:23:53 volumio volumio[783]: at /volumio/app/plugins/music_service/upnp_browser/index.js:596:21
May 24 10:23:53 volumio volumio[783]: at Parser. (/volumio/node_modules/xml2js/lib/xml2js.js:489:18)
May 24 10:23:53 volumio volumio[783]: at emitOne (events.js:96:13)
May 24 10:23:53 volumio volumio[783]: at Parser.emit (events.js:188:7)
May 24 10:23:53 volumio volumio[783]: at Object.onclosetag (/volumio/node_modules/xml2js/lib/xml2js.js:447:26)
May 24 10:23:53 volumio volumio[783]: at emit (/volumio/node_modules/sax/lib/sax.js:640:35)
May 24 10:23:53 volumio volumio[783]: at emitNode (/volumio/node_modules/sax/lib/sax.js:645:5)
May 24 10:23:53 volumio volumio[783]: at closeTag (/volumio/node_modules/sax/lib/sax.js:905:7)
May 24 10:23:53 volumio volumio[783]: at Object.write (/volumio/node_modules/sax/lib/sax.js:1452:13)
May 24 10:23:53 volumio volumio[783]: at Parser.exports.Parser.Parser.parseString (/volumio/node_modules/xml2js/lib/xml2js.js:508:31)
May 24 10:23:53 volumio volumio[783]: at Parser.parseString (/volumio/node_modules/xml2js/lib/xml2js.js:7:59)
May 24 10:23:53 volumio volumio[783]: at /volumio/app/plugins/music_service/upnp_browser/index.js:595:24
May 24 10:23:53 volumio volumio[783]: at Request.handleRequestResponse [as _callback] (/volumio/node_modules/unirest/index.js:463:26)
May 24 10:23:53 volumio volumio[783]: at Request.self.callback (/volumio/node_modules/unirest/node_modules/request/request.js:187:22)
May 24 10:23:53 volumio volumio[783]: at emitTwo (events.js:106:13)
```
The tracebacks continue, with a few interruptions here & there until this
```
May 24 11:38:48 volumio volumio[783]: Upnp client error: Error: This socket has been ended by the other party
May 24 11:39:17 volumio wpa_supplicant[710]: wlan0: WPA: Group rekeying completed with 30:91:8f:4b:40:59 [GTK=TKIP]
May 24 11:39:55 volumio volumio-remote-updater[448]: [2018-05-24 11:39:55] [disconnect] Disconnect close local:[1008,Pong timeout] remote:[1006]
May 24 11:40:00 volumio volumio-remote-updater[448]: [2018-05-24 11:40:00] [connect] Successful connection
May 24 11:40:13 volumio volumio-remote-updater[448]: [2018-05-24 11:40:13] [connect] Successful connection
May 24 11:40:28 volumio volumio-remote-updater[448]: [2018-05-24 11:40:28] [connect] Successful connection
May 24 11:40:34 volumio volumio[783]: info: [LastFM] Error: Authentication Failed - You do not have permissions to access the service
May 24 11:40:37 volumio volumio[783]: error: error
May 24 11:40:37 volumio volumio[783]: error: error
May 24 11:40:37 volumio volumio[783]: error: error
May 24 11:40:37 volumio volumio[783]: error: error
May 24 11:40:37 volumio volumio[783]: error: error
May 24 11:40:37 volumio volumio[783]: error: error
May 24 11:40:37 volumio volumio[783]: error: error
May 24 11:40:43 volumio volumio-remote-updater[448]: [2018-05-24 11:40:43] [connect] Successful connection
May 24 11:40:58 volumio volumio-remote-updater[448]: [2018-05-24 11:40:58] [connect] Successful connection
May 24 11:41:07 volumio volumio[783]: Upnp client error: Error: This socket has been ended by the other party
May 24 11:41:10 volumio volumio[783]: error: error
May 24 11:41:10 volumio volumio[783]: error: error
May 24 11:41:10 volumio volumio[783]: error: error
```
It goes on like this with upnp problems now mixed with tracebacks, then the upnp problems dominate the log after about May 24 12:46:38, until May 24 15:55:43 when the tracebacks come back. A few hours later, anohter change of behaviour
```
May 24 17:06:40 volumio volumio-remote-updater[448]: [2018-05-24 17:06:40] [connect] Successful connection
May 24 17:06:55 volumio volumio-remote-updater[448]: [2018-05-24 17:06:55] [connect] Successful connection
May 24 17:07:10 volumio volumio-remote-updater[448]: [2018-05-24 17:07:10] [connect] Successful connection
May 24 17:07:25 volumio volumio-remote-updater[448]: [2018-05-24 17:07:25] [connect] Successful connection
May 24 17:07:45 volumio volumio-remote-updater[448]: [2018-05-24 17:07:45] [info] Error getting remote endpoint: system:107 (Transport endpoint is not connected)
May 24 17:07:45 volumio volumio-remote-updater[448]: [2018-05-24 17:07:45] [error] handle_connect error: Timer Expired
May 24 17:08:00 volumio volumio-remote-updater[448]: [2018-05-24 17:08:00] [info] Error getting remote endpoint: system:107 (Transport endpoint is not connected)
May 24 17:08:00 volumio volumio-remote-updater[448]: [2018-05-24 17:08:00] [error] handle_connect error: Timer Expired
May 24 17:08:15 volumio volumio-remote-updater[448]: [2018-05-24 17:08:15] [info] Error getting remote endpoint: system:107 (Transport endpoint is not connected)
May 24 17:08:15 volumio volumio-remote-updater[448]: [2018-05-24 17:08:15] [error] handle_connect error: Timer Expired
May 24 17:08:30 volumio volumio-remote-updater[448]: [2018-05-24 17:08:30] [info] Error getting remote endpoint: system:107 (Transport endpoint is not connected)
May 24 17:08:30 volumio volumio-remote-updater[448]: [2018-05-24 17:08:30] [error] handle_connect error: Timer Expired
May 24 17:08:45 volumio volumio-remote-updater[448]: [2018-05-24 17:08:45] [info] Error getting remote endpoint: system:107 (Transport endpoint is not connected)
May 24 17:08:45 volumio volumio-remote-updater[448]: [2018-05-24 17:08:45] [error] handle_connect error: Timer Expired
May 24 17:09:00 volumio volumio-remote-updater[448]: [2018-05-24 17:09:00] [info] Error getting remote endpoint: system:107 (Transport endpoint is not connected)
May 24 17:09:00 volumio volumio-remote-updater[448]: [2018-05-24 17:09:00] [error] handle_connect error: Timer Expired
May 24 17:09:15 volumio volumio-remote-updater[448]: [2018-05-24 17:09:15] [info] Error getting remote endpoint: system:107 (Transport endpoint is not connected)
May 24 17:09:15 volumio volumio-remote-updater[448]: [2018-05-24 17:09:15] [error] handle_connect error: Timer Expired
```
This continues with the odd traceback until the vrestart
```
May 25 10:33:20 volumio volumio[5021]: info: -------------------------------------------
May 25 10:33:20 volumio volumio[5021]: info: -----            Volumio2              ----
May 25 10:33:20 volumio volumio[5021]: info: -------------------------------------------
May 25 10:33:20 volumio volumio[5021]: info: -----          System startup          ----
May 25 10:33:20 volumio volumio[5021]: info: -------------------------------------------
```
what happens next may be helfpul for finding the bug ( @volumio you may be interested in this)
```
May 25 10:34:03 volumio volumio[5021]: info: BOOT COMPLETED
May 25 10:34:03 volumio volumio[5021]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
May 25 10:34:03 volumio volumio[5021]: info: CoreCommandRouter::Close All Modals sent
May 25 10:34:03 volumio volumio-remote-updater[448]: [2018-05-25 10:34:03] [connect] Successful connection
May 25 10:34:03 volumio volumio[5021]: Express server listening on port 3000
May 25 10:34:03 volumio volumio[5021]: Volumio Calling Home
May 25 10:34:04 volumio volumio[5021]: info: GPIO-Buttons started
May 25 10:34:04 volumio volumio[5021]: info: CoreStateMachine::resetVolumioState
May 25 10:34:04 volumio volumio[5021]: info: CoreStateMachine::getcurrentVolume
May 25 10:34:04 volumio volumio[5021]: info: CoreCommandRouter::volumioRetrievevolume
May 25 10:34:04 volumio volumio[5021]: info: CoreStateMachine::updateTrackBlock
May 25 10:34:04 volumio volumio[5021]: info: CorePlayQueue::getTrackBlock
May 25 10:34:05 volumio volumio[5021]: info: Setting Device type: Raspberry PI
May 25 10:34:05 volumio volumio[5021]: { Error: Command failed: /usr/bin/aplay --device=plughw:1,0 /volumio/app/startup.wav
May 25 10:34:05 volumio volumio[5021]: aplay: main:722: audio open error: Device or resource busy
May 25 10:34:05 volumio volumio[5021]: at ChildProcess.exithandler (child_process.js:204:12)
May 25 10:34:05 volumio volumio[5021]: at emitTwo (events.js:106:13)
May 25 10:34:05 volumio volumio[5021]: at ChildProcess.emit (events.js:191:7)
May 25 10:34:05 volumio volumio[5021]: at maybeClose (internal/child_process.js:891:16)
May 25 10:34:05 volumio volumio[5021]: at Socket. (internal/child_process.js:342:11)
May 25 10:34:05 volumio volumio[5021]: at emitOne (events.js:96:13)
May 25 10:34:05 volumio volumio[5021]: at Socket.emit (events.js:188:7)
May 25 10:34:05 volumio volumio[5021]: at Pipe._handle.close [as _onclose] (net.js:497:12)
May 25 10:34:05 volumio volumio[5021]: killed: false,
May 25 10:34:05 volumio volumio[5021]: code: 1,
May 25 10:34:05 volumio volumio[5021]: signal: null,
May 25 10:34:05 volumio volumio[5021]: cmd: '/usr/bin/aplay --device=plughw:1,0 /volumio/app/startup.wav' }
May 25 10:34:05 volumio volumio[5021]: info: CoreCommandRouter::Close All Modals sent
May 25 10:34:05 volumio volumio[5021]: info: MPD running with PID501 ,establishing connection
May 25 10:34:06 volumio volumio-remote-updater[448]: [2018-05-25 10:34:06] [connect] WebSocket Connection 127.0.0.1:3000 v-2 "WebSocket++/0.5.1" /socket.io/?EIO=4&transport=websocket&t=1527244443 101
May 25 10:34:06 volumio volumio[5021]: info: VolumeController:: Volume=49 Mute =false
May 25 10:34:06 volumio volumio[5021]: info: CoreStateMachine::pushState
May 25 10:34:06 volumio volumio[5021]: info: CoreStateMachine::getState
May 25 10:34:06 volumio volumio[5021]: info: CorePlayQueue::getTrack 0
May 25 10:34:06 volumio volumio[5021]: info: CoreCommandRouter::volumioPushState
May 25 10:34:06 volumio volumio[5021]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
May 25 10:34:06 volumio volumio[5021]: info: interfaceApi::pushState
May 25 10:34:06 volumio volumio[5021]: info: Volumio called home
May 25 10:34:06 volumio volumio[5021]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , checkAudioDeviceAvailable
May 25 10:34:07 volumio volumio[5021]: Upnp client error: Error: This socket has been ended by the other party
May 25 10:34:07 volumio volumio[5021]: info: Reloading queue from file
May 25 10:34:08 volumio volumio[5021]: info: CoreStateMachine::setRepeat null single undefined
May 25 10:34:08 volumio volumio[5021]: info: CoreStateMachine::pushState
May 25 10:34:08 volumio volumio[5021]: info: CoreStateMachine::getState
May 25 10:34:08 volumio volumio[5021]: info: CorePlayQueue::getTrack 0
May 25 10:34:08 volumio volumio[5021]: info: CoreCommandRouter::volumioPushState
May 25 10:34:08 volumio volumio[5021]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
May 25 10:34:08 volumio volumio[5021]: info: interfaceApi::pushState
May 25 10:34:08 volumio volumio[5021]: info: CoreStateMachine::setRandom null
May 25 10:34:08 volumio volumio[5021]: info: CoreStateMachine::pushState
May 25 10:34:08 volumio volumio[5021]: info: CoreStateMachine::getState
May 25 10:34:08 volumio volumio[5021]: info: CorePlayQueue::getTrack 0
May 25 10:34:08 volumio volumio[5021]: info: CoreCommandRouter::volumioPushState
May 25 10:34:08 volumio volumio[5021]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
May 25 10:34:08 volumio volumio[5021]: info: interfaceApi::pushState
May 25 10:34:09 volumio volumio[5021]: error:  TypeError: Cannot read property '0' of undefined
May 25 10:34:09 volumio volumio[5021]: at /volumio/app/plugins/music_service/upnp_browser/index.js:83:67
May 25 10:34:09 volumio volumio[5021]: at /volumio/app/plugins/music_service/upnp_browser/index.js:596:21
May 25 10:34:09 volumio volumio[5021]: at Parser. (/volumio/node_modules/xml2js/lib/xml2js.js:489:18)
May 25 10:34:09 volumio volumio[5021]: at emitOne (events.js:96:13)
May 25 10:34:09 volumio volumio[5021]: at Parser.emit (events.js:188:7)
May 25 10:34:09 volumio volumio[5021]: at Object.onclosetag (/volumio/node_modules/xml2js/lib/xml2js.js:447:26)
May 25 10:34:09 volumio volumio[5021]: at emit (/volumio/node_modules/sax/lib/sax.js:640:35)
May 25 10:34:09 volumio volumio[5021]: at emitNode (/volumio/node_modules/sax/lib/sax.js:645:5)
May 25 10:34:09 volumio volumio[5021]: at closeTag (/volumio/node_modules/sax/lib/sax.js:905:7)
May 25 10:34:09 volumio volumio[5021]: at Object.write (/volumio/node_modules/sax/lib/sax.js:1452:13)
May 25 10:34:09 volumio volumio[5021]: at Parser.exports.Parser.Parser.parseString (/volumio/node_modules/xml2js/lib/xml2js.js:508:31)
May 25 10:34:09 volumio volumio[5021]: at Parser.parseString (/volumio/node_modules/xml2js/lib/xml2js.js:7:59)
May 25 10:34:09 volumio volumio[5021]: at /volumio/app/plugins/music_service/upnp_browser/index.js:595:24
May 25 10:34:09 volumio volumio[5021]: at Request.handleRequestResponse [as _callback] (/volumio/node_modules/unirest/index.js:463:26)
May 25 10:34:09 volumio volumio[5021]: at Request.self.callback (/volumio/node_modules/unirest/node_modules/request/request.js:187:22)
May 25 10:34:09 volumio volumio[5021]: at emitTwo (events.js:106:13)
```
and then it's tracebacks all the way to the end.

**Comment by xipmix** [comment]
Questions
1.  how did you decide you could not reach volumio.local ? By trying to access it from e.g. a phone? Or by trying ```ping volumio.local``` ?
2. After a vrestart, can you always play a webradio? How long until it breaks again (roughly)?
3. Is it possible there was another device on the network with the same IP address as your volumio?

**Comment by elcuevero** [comment]
1. could not reach volumio.lan from phone or volumo.local from PC. Could
open ssh session and send command.
2. 9 out 10 I could play radio after a vrestart.Time to break again was
random, sometimes I could switch between 5 stations and sometimes on the
next one selected.
3. I have the IP reserved for the Raspi on my network.

**Comment by elcuevero** [comment]
Will do and post back, thanks.

**Comment by elcuevero** [comment]
Ok, removed most of the plugins I had and it did not hang. Reinstalled two
plugins (TuneIn/Radioparadise) and was able to duplicate the issue, removed
them and performed reboot, so far so good. Reinstalled Tunein and doing
testing now. FWIW I did not reinstall lastfm.

**Comment by xipmix** [comment]
Great work, thanks for the update.
